# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0004_post_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('products', models.TextField()),
                ('phone_number', models.IntegerField(max_length=60)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jirani.Location')),
            ],
        ),
    ]
