# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0008_auto_20181018_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
