# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0009_auto_20181018_0906'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Neighborhood',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['email']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
