# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0011_auto_20181018_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
