# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0012_business_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
