# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0014_business_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='profile',
        ),
    ]
