# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0015_remove_business_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
