# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0018_auto_20181019_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='user',
        ),
    ]
