# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0019_remove_business_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=60)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jirani.Post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jirani.Profile')),
            ],
        ),
    ]
