# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0020_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
